import { Inter } from "next/font/google";
import "../globals.css";
import { Arimo } from "next/font/google";
import { Rubik } from "next/font/google";

const arimo = Arimo({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-arimo",
});
const rubik = Rubik({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-rubik",
});
import { NextIntlClientProvider, useMessages } from "next-intl";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// import {NextIntlClientProvider, useMessages} from 'next-intl';
// import {notFound} from 'next/navigation';

export default function LocaleLayout({ children, params: { locale } }) {
  // ...

  // Receive messages provided in `i18n.ts`
  const messages = useMessages();

  return (
    <html lang={locale}>
      <body className={arimo.variable + rubik.variable}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
